ALTER TABLE "discovery_run_document" DROP CONSTRAINT "ck_discovery_run_document_status";--> statement-breakpoint
ALTER TABLE "discovery_run_document" ADD CONSTRAINT "ck_discovery_run_document_status" CHECK ("discovery_run_document"."status" in ('DISCOVERED', 'DUPLICATE', 'EXCLUDED', 'READY_FOR_REVIEW', 'FAILED'));--> statement-breakpoint
INSERT INTO "skill_version" (
	"id", "skill_id", "version", "name", "kind", "description", "input_schema", "output_schema", "allowed_tools", "side_effect", "timeout_ms", "max_attempts", "risk_level", "status"
) VALUES
	('screen_evidence_eligibility@1.0.0', 'screen_evidence_eligibility', '1.0.0', 'Screen evidence eligibility', 'DETERMINISTIC', 'Require source-grounded target disease and gene mentions before model extraction.', '{"type":"object"}'::jsonb, '{"type":"object"}'::jsonb, '[]'::jsonb, 'STAGING_WRITE', 5000, 1, 'HIGH', 'ACTIVE'),
	('recognize_evidence_entities@1.0.0', 'recognize_evidence_entities', '1.0.0', 'Recognize evidence entities', 'DETERMINISTIC', 'Collect source-grounded entity mentions from extracted claims.', '{"type":"object"}'::jsonb, '{"type":"object"}'::jsonb, '[]'::jsonb, 'NONE', 5000, 1, 'HIGH', 'ACTIVE'),
	('normalize_evidence_entities@1.0.0', 'normalize_evidence_entities', '1.0.0', 'Normalize evidence entities', 'DETERMINISTIC', 'Attach recognized entities to a reviewed catalog target.', '{"type":"object"}'::jsonb, '{"type":"object"}'::jsonb, '[]'::jsonb, 'NONE', 5000, 1, 'HIGH', 'ACTIVE'),
	('extract_treatment_relationship@1.0.0', 'extract_treatment_relationship', '1.0.0', 'Extract treatment relationship', 'DETERMINISTIC', 'Create an explicit review-only relationship proposal.', '{"type":"object"}'::jsonb, '{"type":"object"}'::jsonb, '[]'::jsonb, 'NONE', 5000, 1, 'HIGH', 'ACTIVE')
ON CONFLICT ("skill_id", "version") DO NOTHING;--> statement-breakpoint
INSERT INTO "agent_version" (
	"id", "agent_id", "version", "name", "goal", "instructions_version", "allowed_skill_versions", "allowed_tools", "model_configuration", "token_and_cost_budget", "stop_conditions", "handoff_conditions", "failure_policy", "status"
) VALUES
	('eligibility-agent@1.0.0', 'eligibility-agent', '1.0.0', 'Evidence Eligibility Agent', 'Decide whether a source may enter extraction and retain structured reasons.', 'evidex-eligibility-v1', '["screen_evidence_eligibility@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["include","exclude","needs_human"]'::jsonb, '["human_review"]'::jsonb, '{"maxAttempts":1,"onFailure":"NEEDS_HUMAN"}'::jsonb, 'ACTIVE'),
	('entity-recognition-agent@1.0.0', 'entity-recognition-agent', '1.0.0', 'Entity Recognition Agent', 'Recognize only entities present in extracted source-grounded claims.', 'evidex-entity-recognition-v1', '["recognize_evidence_entities@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["entities_recognized"]'::jsonb, '["human_review"]'::jsonb, '{"maxAttempts":1,"onFailure":"NEEDS_HUMAN"}'::jsonb, 'ACTIVE'),
	('normalization-agent@1.0.0', 'normalization-agent', '1.0.0', 'Evidence Normalization Agent', 'Map recognized evidence entities to the reviewed catalog target.', 'evidex-normalization-v1', '["normalize_evidence_entities@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["entities_normalized"]'::jsonb, '["human_review"]'::jsonb, '{"maxAttempts":1,"onFailure":"NEEDS_HUMAN"}'::jsonb, 'ACTIVE'),
	('relationship-agent@1.0.0', 'relationship-agent', '1.0.0', 'Relationship Extraction Agent', 'Build review-only treatment relationship proposals.', 'evidex-relationship-v1', '["extract_treatment_relationship@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["relationship_proposed"]'::jsonb, '["human_review"]'::jsonb, '{"maxAttempts":1,"onFailure":"NEEDS_HUMAN"}'::jsonb, 'ACTIVE'),
	('grading-agent@1.0.0', 'grading-agent', '1.0.0', 'Evidence Grading Agent', 'Propose an evidence level without approving it.', 'evidex-grading-v1', '["propose_evidence_level@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["grade_proposed"]'::jsonb, '["human_review"]'::jsonb, '{"maxAttempts":1,"onFailure":"NEEDS_HUMAN"}'::jsonb, 'ACTIVE'),
	('ingestion-qa-agent@1.0.0', 'ingestion-qa-agent', '1.0.0', 'Ingestion QA Agent', 'Validate traceability and review readiness without approval or publication.', 'evidex-ingestion-qa-v1', '["validate_draft_completeness@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["qa_complete","blocking_issue"]'::jsonb, '["human_review"]'::jsonb, '{"maxAttempts":1,"onFailure":"NEEDS_HUMAN"}'::jsonb, 'ACTIVE'),
	('question-understanding-agent@1.0.0', 'question-understanding-agent', '1.0.0', 'Question Understanding Agent', 'Resolve and normalize a question against one locked published catalog.', 'evidex-question-understanding-v1', '["understand_question@1.0.0","normalize_query@1.0.0"]'::jsonb, '["knowledge.read"]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["question_resolved","clarification_required","out_of_scope"]'::jsonb, '["safe_failure"]'::jsonb, '{"maxAttempts":1,"onFailure":"FAILED"}'::jsonb, 'ACTIVE'),
	('retrieval-planning-agent@1.0.0', 'retrieval-planning-agent', '1.0.0', 'Retrieval Planning Agent', 'Create a release-locked structured retrieval plan.', 'evidex-retrieval-planning-v1', '["build_retrieval_plan@1.0.0"]'::jsonb, '["knowledge.read"]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["plan_built"]'::jsonb, '["safe_failure"]'::jsonb, '{"maxAttempts":1,"onFailure":"FAILED"}'::jsonb, 'ACTIVE'),
	('evidence-retrieval-agent@1.0.0', 'evidence-retrieval-agent', '1.0.0', 'Evidence Retrieval Agent', 'Build an Evidence Pack only from the locked published release.', 'evidex-evidence-retrieval-v1', '["build_evidence_pack@1.0.0"]'::jsonb, '["knowledge.read"]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["evidence_pack_built"]'::jsonb, '["safe_failure"]'::jsonb, '{"maxAttempts":2,"onFailure":"FAILED"}'::jsonb, 'ACTIVE'),
	('evidence-analysis-agent@1.0.0', 'evidence-analysis-agent', '1.0.0', 'Evidence Analysis Agent', 'Organize evidence directions, levels and limitations without altering them.', 'evidex-evidence-analysis-v1', '["analyze_evidence@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["analysis_complete"]'::jsonb, '["safe_failure"]'::jsonb, '{"maxAttempts":1,"onFailure":"FAILED"}'::jsonb, 'ACTIVE'),
	('answer-composition-agent@1.0.0', 'answer-composition-agent', '1.0.0', 'Answer Composition Agent', 'Compose a structured answer constrained to one Evidence Pack.', 'evidex-answer-v1', '["compose_evidence_answer@1.0.0"]'::jsonb, '[]'::jsonb, '{"provider":"evolink","model":"gpt-5.6-terra"}'::jsonb, '{"maxOutputTokens":6000}'::jsonb, '["answer_composed"]'::jsonb, '["summary_unavailable"]'::jsonb, '{"maxAttempts":2,"onFailure":"SUMMARY_UNAVAILABLE"}'::jsonb, 'ACTIVE'),
	('answer-qa-agent@1.0.0', 'answer-qa-agent', '1.0.0', 'Answer QA Agent', 'Validate structured output and references before public return.', 'evidex-answer-qa-v1', '["validate_answer@1.0.0"]'::jsonb, '[]'::jsonb, '{"mode":"deterministic"}'::jsonb, '{"maxOutputTokens":0}'::jsonb, '["answer_valid","answer_rejected"]'::jsonb, '["summary_unavailable"]'::jsonb, '{"maxAttempts":1,"onFailure":"SUMMARY_UNAVAILABLE"}'::jsonb, 'ACTIVE')
ON CONFLICT ("agent_id", "version") DO NOTHING;--> statement-breakpoint
INSERT INTO "workflow_version" (
	"id", "workflow_id", "version", "name", "kind", "definition", "status"
) VALUES (
	'single-pubmed-v2', 'single-pubmed', '2.0.0', 'Governed multi-agent PubMed ingestion', 'UPSTREAM', '{"steps":["fetch_pubmed_metadata","deduplicate_source_document","screen_evidence_eligibility","extract_evidence_claims","recognize_evidence_entities","normalize_evidence_entities","extract_treatment_relationship","propose_evidence_level","validate_draft_completeness","human_review"]}'::jsonb, 'ACTIVE'
) ON CONFLICT ("workflow_id", "version") DO NOTHING;--> statement-breakpoint
UPDATE "workflow_version" SET "status" = 'DEPRECATED' WHERE "workflow_id" = 'single-pubmed' AND "version" <> '2.0.0';--> statement-breakpoint
UPDATE "workflow_version"
SET "definition" = '{"trigger":"MANUAL","steps":["scope_preview","search_pubmed","deduplicate_source_document","screen_evidence_eligibility","extract_evidence_claims","recognize_evidence_entities","normalize_evidence_entities","extract_treatment_relationship","propose_evidence_level","validate_draft_completeness","human_review"]}'::jsonb
WHERE "id" = 'pubmed-discovery-v2';
